### ISSUE TITLE
Crashes with no information when files (rfa, rvt, etc.) are of 0 file size/otherwise unreadable.

### ISSUE THREAD

**Issue by misterjmw** [acnicholas/ReVInfo#2]
Issue: Nothing shocking here, but if an RVT is empty, or corrupt, it seems that it crashes ReVInfo and no dialog boxes are presented. Error needs to be caught and handled.

Idea: If file is unreadable (for whatever reason), indicate so in the dialog presented.

**Comment by acnicholas** [comment]
Thanks  @misterjmw

I've added some basic error handling to catch files of the wrong format.
Errors are now handled and displayed in the dialog.

See release: [v1.1.1](https://github.com/acnicholas/ReVInfo/releases/tag/v1.1.1)
